version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: re7
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/re7?schema=public
      NODE_ENV: production
      PORT: 4000
      # Default ganache private key
      PRIVATE_KEY: "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
      API_KEY: ${API_KEY:-prod-key}
      ENABLE_FORK: false
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
        NEXT_PUBLIC_API_KEY: ${API_KEY:-prod-key}
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
      NEXT_PUBLIC_API_KEY: ${API_KEY:-prod-key}
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:

