version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: re7
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/re7?schema=public
      NODE_ENV: production
      PORT: 4000
      RPC_URL: ${RPC_URL:-}
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:

