version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: re7
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      AUTO_SEED_ON_START: true
      DATABASE_URL: postgresql://postgres:postgres@db:5432/re7?schema=public
      NODE_ENV: development
      PORT: 4000
      # Default ganache private key
      PRIVATE_KEY: "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113b37a1f44a8fa7f6fce205b8"
      FORK_RPC_URL: http://127.0.0.1:8545
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:

